apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-container
          image: angular-app:v1  # Use the local Docker image
          ports:
            - containerPort: 80
          imagePullPolicy: Never  # Prevent image pulling from remote

---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: NodePort  # Use NodePort for local development
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Optional: specify a node port for access
