apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-container
          image: angular-app:v1  # Use the local Docker image
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: LoadBalancer
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
